language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: make test

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_deploy:
  - make package
