sudo: false

language: php

env:
  - =foo
  - FOO=bar

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: make test

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_deploy:
  - make package
